# Generated by Django 5.2.8 on 2025-11-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
